Fix test imports
Resolve issue:
ERROR: TypeScript import equals declaration is not supported in strip-only mode
(node:26607) [MODULE_TYPELESS_PACKAGE_JSON] Warning: Module type of file:///Users/rosbo/projects/streamlabs/obs-studio-node/tests/osn-tests/src/test_audio_encoder.ts is not specified and it doesn't parse as CommonJS.
Reparsing as ES module because module syntax was detected. This incurs a performance overhead.
To eliminate this warning, add "type": "module" to /Users/rosbo/projects/streamlabs/obs-studio-node/package.json.
(Use `Electron --trace-warnings ...` to show where the warning was created)